"""
Davlatlar ro'yxati — O'zbekcha nomlar va flaglar
PHP: contries.php faylidan olingan
"""

COUNTRY_NAMES = {
    "AE": "BAA 🇦🇪",
    "UA": "Ukraina 🇺🇦",
    "BH": "Bahrayn 🇧🇭",
    "DE": "Germaniya 🇩🇪",
    "AO": "Angola 🇦🇴",
    "GE": "Gruziya 🇬🇪",
    "GB": "Buyuk Britaniya 🇬🇧",
    "IR": "Eron 🇮🇷",
    "KG": "Qirgʻiziston 🇰🇬",
    "KZ": "Qozogʻiston 🇰🇿",
    "KW": "Quvayt 🇰🇼",
    "MZ": "Mozambik 🇲🇿",
    "OM": "Ummon 🇴🇲",
    "NE": "Niger 🇳🇪",
    "PS": "Falastin 🇵🇸",
    "PG": "Papua Yangi Gvineya 🇵🇬",
    "QA": "Qatar 🇶🇦",
    "SB": "Solomon orollari 🇸🇧",
    "TW": "Tayvan 🇹🇼",
    "TR": "Turkiya 🇹🇷",
    "YE": "Yaman 🇾🇪",
    "JO": "Iordaniya 🇯🇴",
    "US": "AQSH 🇺🇸",
    "RO": "Ruminiya 🇷🇴",
    "HN": "Gonduras 🇭🇳",
    "AW": "Aruba 🇦🇼",
    "FR": "Fransiya 🇫🇷",
    "IL": "Isroil 🇮🇱",
    "TJ": "Tojikiston 🇹🇯",
    "CH": "Shveytsariya 🇨🇭",
    "IQ": "Iroq 🇮🇶",
    "TN": "Tunis 🇹🇳",
    "CF": "Markaziy Afrika 🇨🇫",
    "MM": "Myanma 🇲🇲",
    "ZA": "Janubiy Afrika 🇿🇦",
    "CM": "Kamerun 🇨🇲",
    "DZ": "Jazoir 🇩🇿",
    "NG": "Nigeriya 🇳🇬",
    "BG": "Bolgariya 🇧🇬",
    "ML": "Mali 🇲🇱",
    "MX": "Meksika 🇲🇽",
    "GH": "Gana 🇬🇭",
    "PT": "Portugaliya 🇵🇹",
    "AZ": "Ozarbayjon 🇦🇿",
    "ES": "Ispaniya 🇪🇸",
    "NL": "Niderlandiya 🇳🇱",
    "CU": "Kuba 🇨🇺",
    "FK": "Folklend orollari 🇫🇰",
    "AR": "Argentina 🇦🇷",
    "UZ": "Oʻzbekiston 🇺🇿",
    "LY": "Liviya 🇱🇾",
    "PE": "Peru 🇵🇪",
    "HU": "Vengriya 🇭🇺",
    "VE": "Venesuela 🇻🇪",
    "CO": "Kolumbiya 🇨🇴",
    "BA": "Bosniya 🇧🇦",
    "SE": "Shvetsiya 🇸🇪",
    "AM": "Armaniston 🇦🇲",
    "SV": "Salvador 🇸🇻",
    "JP": "Yaponiya 🇯🇵",
    "SL": "Syerra-Leone 🇸🇱",
    "CZ": "Chexiya 🇨🇿",
    "ID": "Indoneziya 🇮🇩",
    "PL": "Polsha 🇵🇱",
    "BN": "Bruney 🇧🇳",
    "MG": "Madagaskar 🇲🇬",
    "NO": "Norvegiya 🇳🇴",
    "KR": "Janubiy Koreya 🇰🇷",
    "AU": "Avstraliya 🇦🇺",
    "TC": "Turks va Kaykos 🇹🇨",
    "EC": "Ekvador 🇪🇨",
    "MY": "Malayziya 🇲🇾",
    "AG": "Antigua va Barbuda 🇦🇬",
    "CI": "Kot-d'Ivuar 🇨🇮",
    "KE": "Keniya 🇰🇪",
    "BJ": "Benin 🇧🇯",
    "GD": "Grenada 🇬🇩",
    "NI": "Nikaragua 🇳🇮",
    "WS": "Samoa 🇼🇸",
    "TO": "Tonga 🇹🇴",
    "CA": "Kanada 🇨🇦",
    "FI": "Finlandiya 🇫🇮",
    "MN": "Mongoliya 🇲🇳",
    "GY": "Gayana 🇬🇾",
    "SZ": "Svazilend 🇸🇿",
    "PK": "Pokiston 🇵🇰",
    "CN": "Xitoy 🇨🇳",
    "ZM": "Zambiya 🇿🇲",
    "VC": "Sent-Vinsent 🇻🇨",
    "BD": "Bangladesh 🇧🇩",
    "ZW": "Zimbabve 🇿🇼",
    "SC": "Seyshel 🇸🇨",
    "TD": "Chad 🇹🇩",
    "EG": "Misr 🇪🇬",
    "TH": "Tailand 🇹🇭",
    "PR": "Puerto-Riko 🇵🇷",
    "TM": "Turkmaniston 🇹🇲",
    "BR": "Braziliya 🇧🇷",
    "SG": "Singapur 🇸🇬",
    "LB": "Livan 🇱🇧",
    "FO": "Farerlar 🇫🇴",
    "LR": "Liberiya 🇱🇷",
    "VU": "Vanuatu 🇻🇺",
    "UY": "Urugvay 🇺🇾",
    "PY": "Paragvay 🇵🇾",
    "HT": "Gaiti 🇭🇹",
    "GL": "Grenlandiya 🇬🇱",
    "IN": "Hindiston 🇮🇳",
    "SY": "Suriya 🇸🇾",
    "MT": "Malta 🇲🇹",
    "SA": "Saudiya Arabistoni 🇸🇦",
    "SS": "Janubiy Sudan 🇸🇸",
    "BS": "Bagama orollari 🇧🇸",
    "HK": "Gonkong 🇭🇰",
    "NC": "Yangi Kaledoniya 🇳🇨",
    "IT": "Italiya 🇮🇹",
    "ME": "Chernogoriya 🇲🇪",
    "MR": "Mavritaniya 🇲🇷",
    "KM": "Komor orollari 🇰🇲",
    "PA": "Panama 🇵🇦",
    "ST": "San-Tome va Prinsipi 🇸🇹",
    "TL": "Sharqiy Timor 🇹🇱",
    "MV": "Maldiv 🇲🇻",
    "AL": "Albaniya 🇦🇱",
    "RW": "Ruanda 🇷🇼",
    "CY": "Kipr 🇨🇾",
    "XK": "Kosovo 🇽🇰",
    "LC": "Sent-Lyusiya 🇱🇨",
    "TZ": "Tanzaniya 🇹🇿",
    "MW": "Malavi 🇲🇼",
    "BE": "Belgiya 🇧🇪",
    "BW": "Botsvana 🇧🇼",
    "NZ": "Yangi Zelandiya 🇳🇿",
    "CK": "Kuk orollari 🇨🇰",
    "LK": "Shri-Lanka 🇱🇰",
    "SI": "Sloveniya 🇸🇮",
    "RE": "Reyunyon 🇷🇪",
    "GT": "Gvatemala 🇬🇹",
    "BO": "Boliviya 🇧🇴",
    "YT": "Mayotta 🇾🇹",
    "MO": "Makao 🇲🇴",
    "DJ": "Jibuti 🇩🇯",
    "MD": "Moldova 🇲🇩",
    "CL": "Chili 🇨🇱",
    "GM": "Gambiya 🇬🇲",
    "NA": "Namibiya 🇳🇦",
    "PH": "Filippin 🇵🇭",
    "SO": "Somali 🇸🇴",
    "KH": "Kambodja 🇰🇭",
    "EE": "Estoniya 🇪🇪",
    "MU": "Mavrikiy 🇲🇺",
    "SN": "Senegal 🇸🇳",
    "ET": "Efiopiya 🇪🇹",
    "CV": "Kabo-Verde 🇨🇻",
    "BF": "Burkina-Faso 🇧🇫",
    "GW": "Gvineya-Bisau 🇬🇼",
    "LT": "Litva 🇱🇹",
    "FJ": "Fiji 🇫🇯",
    "BI": "Burundi 🇧🇮",
    "GR": "Gretsiya 🇬🇷",
    "AT": "Avstriya 🇦🇹",
    "SD": "Sudan 🇸🇩",
    "LV": "Latviya 🇱🇻",
    "TT": "Trinidad va Tobago 🇹🇹",
    "LU": "Lyuksemburg 🇱🇺",
    "MA": "Marokash 🇲🇦",
    "LA": "Laos 🇱🇦",
    "CR": "Kosta-Rika 🇨🇷",
    "DM": "Dominika 🇩🇲",
    "BB": "Barbados 🇧🇧",
    "BZ": "Beliz 🇧🇿",
    "BY": "Belarus 🇧🇾",
    "BM": "Bermuda 🇧🇲",
    "GN": "Gvineya 🇬🇳",
    "CW": "Kyurasao 🇨🇼",
    "KI": "Kiribati 🇰🇮",
    "HR": "Xorvatiya 🇭🇷",
    "GQ": "Ekvatorial Gvineya 🇬🇶",
    "MK": "Shimoliy Makedoniya 🇲🇰",
    "NR": "Nauru 🇳🇷",
    "SK": "Slovakiya 🇸🇰",
    "SR": "Surinam 🇸🇷",
    "UG": "Uganda 🇺🇬",
    "NP": "Nepal 🇳🇵",
    "AF": "Afgʻoniston 🇦🇫",
    "RU": "Rossiya 🇷🇺",
}


def get_country_name(code: str) -> str:
    return COUNTRY_NAMES.get(code.upper(), f"🏳️ {code}")
